### ISSUE TITLE
Is it possible to use CommonAPI proxy with legacy DBus services without ObjectManager interface?

### ISSUE THREAD

**Issue by aleksei-timofeyev** [GENIVI/capicxx-dbus-tools#1]
Hi,

Is it possible to use CommonAPI proxy with legacy DBus services without ObjectManager interface?
I want to use CommonAPI to communicate with NodeHealthMonitor.

Regards,
Aleksei

**Comment by aleksei-timofeyev** [comment]
It was be possible before 3.x.x version:
>Each config file may have an arbitrary number of entries of the following format, with each entry being separated from the others by a newline:
>
>[CommonAPI Address]
>dbus_connection=<valid D-Bus Connection Name>
>dbus_object=<valid D-Bus Object Path>
>dbus_interface=<valid D-Bus Interface Name>
>dbus_predefined=<true/false>
>All "dbus_*"-values are optional. For each such omitted value the default value as described above will be used. For "dbus_predefined", the default value is "false".
>
>"dbus_predefined" should be used if the associated service of a proxy is a legacy service that does not provide the "org.freedesktop.DBus.ObjectManager" interface.

**Comment by gunnarx** [comment]
I would also like to know, and @aleksei-timofeyev please contribute some code if you are able to connect Common API to NHM.  (Notify me/us on genivi-projects mailing lists, see lists.genivi.org)

**Comment by GenivivSOMEIPmaintainer** [comment]
With CommonAPI 3 the implementation of the ObjectManager Interface is mandatory.
