### ISSUE TITLE
tutorial - obsolete path

### ISSUE THREAD

**Issue by mateuszzz88** [GENIVI/capicxx-dbus-tools#3]
this tutorial: https://github.com/GENIVI/capicxx-dbus-tools/wiki/CommonAPI-C---D-Bus-in-10-minutes

has: 
`<.>/dbus-1.10.10$ patch -p1 < ../common-api-dbus-runtime/src/dbus-patches/capi-dbus-....`
it should have:
`<.>/dbus-1.10.10$ patch -p1 < ../capicxx-dbus-runtime/src/dbus-patches/capi-dbus-....`
or even better should have:
` for i in ../capicxx-dbus-runtime/src/dbus-patches/*.patch; do patch -p1 < $i; done`

has in CMakeList.txt:
$ENV{RUNTIME_PATH}/capicxx-runtime/
should have:
$ENV{RUNTIME_PATH}/capicxx-core-runtime/

has in HelloWorldClient.cpp and HelloWorldStubImpl.hpp:
#include <v1_0/commonapi/HelloWorldProxy.hpp>
should have:
#include <v1/commonapi/HelloWorldProxy.hpp>
(at least this is what was generated for me)

**Comment by gunnarx** [comment]
I agree and have found this error before.  @GeniviCommonAPImaintainer did not fix yet, so since I have edit capability I made the proposed change for you. Thanks @mateuszzz88 for your contribution - please keep them coming.

**Comment by gunnarx** [comment]
I guess this ticket should be closed?  I had hoped @GeniviCommonAPImaintainer would check that everything is alright and comment on it.

**Comment by ywiyogo** [comment]
No, the missing `-core-` in the path in CMakeLists.txt and the `v1/..` instead of `v1_0/..` doesn't fixed yet.

**Comment by juliandm** [comment]
Hi, i can confirm July 2019: this documentation still needs to be fixed

**Comment by gunnarx** [comment]
:-(  Send a PR and I will merge it...  (I am not the maintainer, but I can merge it for you).

**Comment by gunnarx** [comment]
Oh sorry, it's in the wiki, so no PRs...  OK, I can just edit it. 
Hmm, it seems I edited 2 years ago also (but not all of it apparently).
I think I got all of it now @juliandm

**Comment by juliandm** [comment]
Thank you @gunnarx! This small tweak would still be necessary: 

> <.>/capicxx-dbus-runtime/build$ export PKG_CONFIG_PATH="<my-dbus-path>/dbus-1.8.20"
should be
> <.>/capicxx-dbus-runtime/build$ export PKG_CONFIG_PATH="<my-dbus-path>/dbus-1.10.10"

Also i found that the code generators for the 64bit version (x86_64) didn't work for me. If that's also the case for others, maybe it's worth a look. However with a 32bit version of ubuntu they were running fine.

**Comment by gunnarx** [comment]
OK, fixed.

The runtime error you experienced I imagine could be due to Java version?
See this: https://github.com/GENIVI/capicxx-core-tools/issues/15
(It is mentioned as WARNING in that ticket, but it becomes an ERROR on a later java version)
